--Consulta 4
select
CLIENTE.C_id as ClienteID,
PERSONA.P_nombre as Nombre,
PERSONA.P_apellido as Apellido,
PAQUETE.Pa_Id as Paquete,
SERVICIO.Se_ID as Servicio,
SERVICIO.Se_Nombre as TipoServicio
from factura
INNER JOIN PUBLIC.RESERVASION ON RESERVASION.C_ID=FACTURA.C_ID
INNER JOIN PUBLIC.CLIENTE ON CLIENTE.C_ID=RESERVASION.C_ID
INNER JOIN PUBLIC.PERSONA ON PERSONA.P_ID=CLIENTE.P_ID
INNER JOIN PUBLIC.PAQUETE ON PAQUETE.PA_ID=FACTURA.PA_ID
INNER JOIN PUBLIC.SERVICIO ON SERVICIO.SE_ID=PAQUETE.SE_ID
