--Consulta 1
Select
RESERVASION.RE_ID,
PERSONA.P_nombre as Nombre,
PERSONA.P_apellido as Apellido,
RESERVASION.RE_tipo,
RESERVASION.RE_Fechaentrada
from RESERVASION
INNER JOIN PUBLIC.CLIENTE ON CLIENTE.C_ID=RESERVASION.C_ID
INNER JOIN PUBLIC.PERSONA ON PERSONA.P_ID=CLIENTE.P_ID
WHERE (RESERVASION.RE_Fechaentrada >='1/1/2020' and RESERVASION.RE_Fechaentrada <='31/12/2020')

