
--Consulta 2
Select
SERVICIO.SE_ID,
SERVICIO.SE_NOMBRE AS NOMBRE,
PROMOCION.PRO_NOMBRE,
PROMOCION.PRO_DESCUENTO
FROM PAQUETE
INNER JOIN PUBLIC.SERVICIO ON SERVICIO.SE_ID=PAQUETE.SE_ID
INNER JOIN PUBLIC.PROMOCION ON PROMOCION.PRO_ID=PAQUETE.PRO_ID

